feat: add support for v26 protocol

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -29,7 +29,28 @@ jobs:
           pushd local-setup
           ./start-zk-chains.sh
           popd
+      - name: Extract custom token address
+        run: |
+          echo "Waiting for token deployment..."
+          until docker exec local-setup-zksync-1 test -f /configs/erc20.yaml; do
+            echo "Token config file not found yet, checking again in 5 seconds..."
+            sleep 5
+          done
+
+          echo "Extracting deployed token address from inside zksync container..."
+          CUSTOM_TOKEN_ADDRESS=$(docker exec local-setup-zksync-1 awk -F": " '/tokens:/ {found_tokens=1} found_tokens && /DAI:/ {found_dai=1} found_dai && /address:/ {print $2; exit}' /configs/erc20.yaml)
+
+          if [ -z "$CUSTOM_TOKEN_ADDRESS" ]; then
+            echo "❌ Error: Could not retrieve token address. Exiting."
+            exit 1
+          fi
+
+          echo "Custom token address: $CUSTOM_TOKEN_ADDRESS"
+          # Export the variable so subsequent steps have access to it
+          echo "CUSTOM_TOKEN_ADDRESS=$CUSTOM_TOKEN_ADDRESS" >> $GITHUB_ENV
       - name: Run tests
+        env:
+          CUSTOM_TOKEN_ADDRESS: ${{ env.CUSTOM_TOKEN_ADDRESS }}
         run: make run-tests-on-eth-based-chain
 
   non-eth-based-chain-test:
@@ -50,5 +71,26 @@ jobs:
           pushd local-setup
           ./start-zk-chains.sh
           popd
+      - name: Extract custom token address
+        run: |
+          echo "Waiting for token deployment..."
+          until docker exec local-setup-zksync-1 test -f /configs/erc20.yaml; do
+            echo "Token config file not found yet, checking again in 5 seconds..."
+            sleep 5
+          done
+
+          echo "Extracting deployed token address from inside zksync container..."
+          CUSTOM_TOKEN_ADDRESS=$(docker exec local-setup-zksync-1 awk -F": " '/tokens:/ {found_tokens=1} found_tokens && /DAI:/ {found_dai=1} found_dai && /address:/ {print $2; exit}' /configs/erc20.yaml)
+
+          if [ -z "$CUSTOM_TOKEN_ADDRESS" ]; then
+            echo "❌ Error: Could not retrieve token address. Exiting."
+            exit 1
+          fi
+
+          echo "Custom token address: $CUSTOM_TOKEN_ADDRESS"
+          # Export the variable so subsequent steps have access to it
+          echo "CUSTOM_TOKEN_ADDRESS=$CUSTOM_TOKEN_ADDRESS" >> $GITHUB_ENV
       - name: Run tests
+        env:
+          CUSTOM_TOKEN_ADDRESS: ${{ env.CUSTOM_TOKEN_ADDRESS }}
         run: make run-tests-on-non-eth-based-chain
